#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

echo "Executing Dotbot..."
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
echo "Dotbot execution completed."

# Function to display a basic progress meter
show_progress() {
    echo -n "["
    for i in $(seq 1 50); do
        if [ "$1" -ge "$i" ]; then
            echo -n "#"
        else
            echo -n " "
        fi
    done
    echo -n "]"
    echo
}

# Function to install zsh
install_zsh() {
    # Detect package manager and install zsh
    if [ "$(uname)" = "Linux" ]; then
        sudo apt update && sudo apt install zsh -y
    elif [ "$(uname)" = "Darwin" ]; then
        brew install zsh
    else
        echo "Unsupported operating system for automatic installation."
        return 1
    fi
}

# Function to set zsh as the default shell
set_default_shell_zsh() {
    ZSH_PATH=$(which zsh)
    if [ -n "$ZSH_PATH" ]; then
        echo "Setting zsh as the default shell. You might need to enter your password."
        chsh -s "$ZSH_PATH"
    else
        echo "zsh installed, but couldn't set it as default. Please set it manually."
        return 1
    fi
}

# Check if zsh is installed
if command -v zsh >/dev/null; then
    show_progress 25
    echo "zsh is already installed. Attempting to set as default shell..."
    show_progress 50
    set_default_shell_zsh
else
    echo "zsh is not installed. Attempting to install and set as default shell..."
    show_progress 25
    install_zsh && set_default_shell_zsh
    show_progress 50
    echo "zsh installed and set as the default shell successfully!!"
    echo "You may need to logout and log back in for shell changes to take effect"
fi